name: google_drive_bottom_navi
description: "Google Drive Bottom Navigation Bar"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/google_drive_bottom_navi

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  hive:
  hive_flutter:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  hive_module:
  june_view:  #@add
  june_view_more: #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/google_drive_bottom_navi/
  uses-material-design: true